apiVersion: v1
kind: ConfigMap
metadata:
  name: sketchxpad-config
  namespace: sketchxpad
data:
  HTTP_BACKEND_URL: "http://http-backend:3000"
  WS_BACKEND_URL: "ws://ws-backend:8080"
  VITE_HTTP_URL: "http://localhost:3000"
  VITE_WS_URL: "ws://localhost:8080"